### ISSUE TITLE
Error duplicating entry 

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/cloneEntry#2]
Here is the message when trying to duplicate an entry:
`Column 'post_type' cannot be null`
And no entry is created.

Tested on 2 v2.27.3 / CloneEntry v4

**Comment by franck-paul** [comment]
J'avais une erreur aussi (avec la 2.28-dev) mais parce qu'un autre plugin foutait le souk. Je n'ai rien trouvé dans cloneEntry.

Je vais tester avec une 2.27.3 pour voir…

**Comment by franck-paul** [comment]
Et RAS avec une 2.27.3 basique, avec juste cloneEntry installé, la duplication se passe bien.

Il va falloir que tu désactives un à un les plugins tiers pour voir celui qui fout le dawa je pense.

**Comment by franck-tomek** [comment]
OK merci, je cherche le fautif, ça va être coton ! :)

**Comment by franck-tomek** [comment]
Ah, j'ai regardé les logs (je n'avais pas pris le temps hier), et j'ai des warnings:
`PHP Warning:  Undefined array key "clone_id" in /public_html/all-blogs/plugins/cloneEntry/src/Manage.php on line 56`
`PHP Warning:  Undefined array key "clone_type" in /public_html/all-blogs/plugins/cloneEntry/src/Manage.php on line 57`
Ça peut aider pour ce bug ?

**Comment by franck-paul** [comment]
Ok je vais vérifier tout ça…

**Comment by franck-paul** [comment]
Est-ce que tu peux me dire côté HTML (avec les outils de dev de FF ou Chrome) comment est le formulaire autour du bouton "Dupliquer cette publication" ?

Pour comparaison chez moi (open-time), ça ressemble à ça :

```html
<form action="index.php?process=Plugin&amp;p=cloneEntry" method="post" name="clone-form" id="clone-form">
<p>
<input type="submit" name="clone" value="Dupliquer cette publication" class="clone">
<input type="hidden" name="process" value="Plugin">
<input type="hidden" name="p" value="cloneEntry">
<input type="hidden" name="clone_id" value="15828">
<input type="hidden" name="clone_type" value="post">
<input type="hidden" name="xd_check" value="b0b027f518b...de70076">
</p>
<p class="form-note no-more-info">Le statut de la nouvelle publication sera positionné à <strong>En attente</strong><br>Ses date et heure seront positionnées à maintenant et son URL devrait refléter ceci.<br>Les catégorie, mots-clés, pièces-jointes et autres propriétés seront préservées.</p>
</form>
```

**Comment by franck-tomek** [comment]
Voici :
```html
<form action="index.php?process=Posts" method="post" name="clone-form" id="clone-form">
<table class="posts-list">
<tbody>
<tr>
<th colspan="2">Titre</th>
</tr>
<tr>
<td class="minimal"><input type="checkbox" name="entries[]" value="43" checked=""></td>
<td>Titre du billet</td>
</tr>
</tbody>
</table>
<p><input type="submit" name="clone" value="Dupliquer"></p>
<p class="form-note">Le statut de la nouvelle publication sera positionné à <strong>En attente</strong><br>Ses date et heure seront positionnées à maintenant et son URL devrait refléter ceci.<br>Les catégorie, mots-clés, pièces-jointes et autres propriétés seront préservées.</p>
<p>
<input type="hidden" name="user_id" value="">
<input type="hidden" name="cat_id" value="">
<input type="hidden" name="status" value="">
<input type="hidden" name="selected" value="">
<input type="hidden" name="attachment" value="">
<input type="hidden" name="month" value="">
<input type="hidden" name="lang" value="">
<input type="hidden" name="sortby" value="post_dt">
<input type="hidden" name="order" value="desc">
<input type="hidden" name="page" value="1">
<input type="hidden" name="nb" value="30">
<input type="hidden" name="process" value="Plugin">
<input type="hidden" name="p" value="cloneEntry">
<input type="hidden" name="full_content" value="true">
<input type="hidden" name="action" value="clone">
<input type="hidden" name="xd_check" value="25eca612c88253abbca2662c9aa2d4eb319307af">
</p>
</form>
```

**Comment by franck-paul** [comment]
Ah bah voilà, t'avais pas précisé le contexte, je pensais que c'était sur la page d'édition d'un billet !

**Comment by franck-paul** [comment]
La nouvelle version corrige ça (sauf pour la duplication de page avec la 2.27, il faut passer par l'édition de la page et utiliser le bouton "Dupliquer" en bas)

**Comment by franck-tomek** [comment]
Huhu, j'avais complètement oublié qu'on pouvait le faire aussi dans le contexte billet, my bad !
OK, c'est noté. Et donc les 2 possibilités / contextes seront ok en 2.28, si je déduis de ton dernier message ?

**Comment by franck-paul** [comment]
Oui
